# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
language: zh-Hans

# hexo-tag-cloud
tag_cloud:
  textFont: Trebuchet MS, Helvetica
  textColour: \#333
  textHeight: 25
  outlineColour: \#ffffff

# Writing
highlight:
  enable: false

#prettify 插件位置
# enable 启用和不启用
# theme 使用prettify高亮主题名称
prettify:
  enable: true
  theme: tomorrow-night-eighties ##这里你可以定义上面下载的themes主题包里面样式文件名，不带.css后缀

lazyload:
  enable: false
  onlypost: false
  loadingImg: /img/loading0_2.gif

# Markdown-it config 表情支持
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
## http://www.cnblogs.com/fsong/p/5929773.html
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: "“”‘’"
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-emoji # add emoji
  anchors:
    level: 2
    collisionSuffix: "v"
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ""
